name: Release (Docker)

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  IMAGE_NAME: worker-vllm

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write         # create GitHub Release
      packages: write         # publish to GHCR
      id-token: write         # provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag
        id: ver
        run: |
          TAG="${GITHUB_REF#refs/tags/}"     # e.g. v1.2.3
          VER="${TAG#v}"                     # 1.2.3
          echo "tag=${TAG}" >> "$GITHUB_OUTPUT"
          echo "version=${VER}" >> "$GITHUB_OUTPUT"
          echo "major_minor=${VER%.*}" >> "$GITHUB_OUTPUT"
          echo "major=${VER%%.*}" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Optional: login to Docker Hub if you want to publish there, too
      - name: Login to Docker Hub
        if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
            ${{ secrets.DOCKERHUB_USERNAME && format('{0}/{1}', secrets.DOCKERHUB_USERNAME, env.IMAGE_NAME) || '' }}
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}},value=${{ steps.ver.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.ver.outputs.version }}
            type=semver,pattern={{major}},value=${{ steps.ver.outputs.version }}
          labels: |
            org.opencontainers.image.title=worker-vllm
            org.opencontainers.image.version=${{ steps.ver.outputs.version }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.repositoryUrl }}

      - name: Build and push (multi-arch)
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          sbom: true
          provenance: mode=max
          build-args: |
            GIT_SHA=${{ github.sha }}

      - name: Summarize images
        id: summary
        run: |
          echo "## Published Images" >> "$GITHUB_STEP_SUMMARY"
          for IMAGE in ${{ steps.meta.outputs.images }}; do
            echo "- \`${IMAGE}@${{ steps.build.outputs.digest }}\`" >> "$GITHUB_STEP_SUMMARY"
          done
          {
            echo "## Container Images"
            for IMAGE in ${{ steps.meta.outputs.images }}; do
              echo "- \`${IMAGE}:${{ steps.ver.outputs.version }}\`"
              echo "- \`${IMAGE}:${{ steps.ver.outputs.major_minor }}\`"
              echo "- \`${IMAGE}:${{ steps.ver.outputs.major }}\`"
              echo "- \`${IMAGE}:latest\`"
            done
            echo ""
            echo "**Digest:** \`${{ steps.build.outputs.digest }}\`"
          } > release-body.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.ver.outputs.tag }}
          generate_release_notes: true
          body_path: release-body.md
